### PR TITLE
feat: Added Start&End flowchart block & try to fix the ArrowComponent.

### PR DESCRIPTION
**Pull request by ExxiDauS**
----------- Things I changed -----------
- [X] Added **Start & End** blocks.
- [X] Try to fix **ArrowComponent**
- [X] Added _test_. Now you can test your flowchart blocks there(?).
- [ ] At _test_ you have to change dir! If anyone can make it run using the dir of the project please do.
----------- Conflicts -----------
- [ ] @KuhnphOn I decided to use FileWriter cause I think it is way easier to use it vs DataOutputStream.

### CODE REVIEW

**Review by KuhnphOn — COMMENTED** [review]
How can I check if that var is declared?
Anyone have ideas?

**Comment by kxxnD04** [comment]
> How can I check if that var is declared? Anyone have ideas?

Maybe add an ArrayList() in Flowchart Main Program then check every time when it run to the process shape?

**Comment by ExxiDauS** [comment]
Or simply just make another shape that declare the var lol.

**Review by pubethSri — APPROVED** [review]
I'm cool with these changes and the matter on using FileWriter, if there are no Errors or conflict yet I think it ok.
and on the topic of checking the existing variable, I suggest using Set to collect variable name that has been declared.

**Pull request merged**
